#!/usr/bin/python3
#
# Automatically splits windows so workspaces are laid out in 2 columns.

from i3ipc import Connection, Event


def move_container(con1, con2):
    con2.command("mark __column-layout")
    con1.command("move window to mark __column-layout")
    con2.command("unmark __column-layout")


def layout(i3, event):
    if event.change == "close":
        for reply in i3.get_workspaces():
            if reply.focused:
                workspace = i3.get_tree().find_by_id(
                    reply.ipc_data["id"]).workspace()

                if len(workspace.nodes) == 1 and len(workspace.nodes[0].nodes) == 1:
                    child = workspace.nodes[0].nodes[0]
                    move_container(child, workspace)
    else:
        # find current window
        # window = i3.get_tree().find_by_id(event.container.id)
        window = i3.get_tree().find_focused()
        # if window exists
        if window is not None:
            # get current workspace from window
            workspace = window.workspace()

            # if workspace exists
            if workspace is not None:
                # if less than 1 node, pass
                if len(workspace.nodes) < 1:
                    pass
                # if exactly 1 node exists
                elif len(workspace.nodes) == 1:
                    workspace.command("splith")
                    # set layout for each node as splith
                    for node in workspace.nodes:
                        node.command("splith")
                # if 2 nodes exist
                elif len(workspace.nodes) == 2:
                    # for each node
                    for node in workspace.nodes:
                        if len(node.nodes) <= 1:
                            node.command("splitv")
                # else if 3 or more nodes exist
                else:
                    for node in workspace.nodes:
                        # splitv here
                        node.command("splitv")


i3 = Connection()
i3.on(Event.WINDOW_NEW, layout)
i3.on(Event.WINDOW_CLOSE, layout)
i3.on(Event.WINDOW_MOVE, layout)
i3.main()
